### ISSUE TITLE
German version: game freezes on monster encounters?

### ISSUE THREAD

**Issue by newcron** [tetracorp/dungeons-of-avalon#4]
Hey there

i played doa2 a lot back at the time (the amiga fun version) but always got stuck in B1 of the lord’s  tower. At that point any monster encounter caused the game to freeze (animations still going but game completely unresponsive to any input)

A decade later I retried in an emulator where i’d get to the same point with the same issue. Game would freeze in exactly the same way. 

Even though the issue occurred twice to me on completely unrelated setups (once amiga  and disc, once in an emulator) I never found any reference to that issue.

i would really love to revisit that game and finish it off for all the time I spent in it as a kid. But I am really not eager to run into the exact same issue again. Can anyone confirm this bug or know a way around it?

**Comment by tetracorp** [comment]
There's only one person I know of who beat DoA2. In [The CRPG Addict's playthrough](https://crpgaddict.blogspot.com/2020/01/dungeons-of-avalon-ii-summary-and-rating.html), a blog commenter named LanHawk beat the game by swapping their save file between German and English versions to avoid bugs. They also noticed a bug where all combat encounters freeze the game, but they say it was on level B2 and in the English version. They may also have used map editing to beat the game.

Some questions for you:

1. Just to be sure, does the monster encounter crash bug occur on B1, the level with a lot of pits?
2. Did you get the version from a cover floppy disk with the magazine, or on the Amiga Fun cover CD-ROM, or from a download?
3. In your version of the game, who the six characters in the adventurer's guild when you start a new game: is it Avance, Aratak, Letahl, Kresta, Mercus, and Beacon; or is it Raymon, Phantic, Mion Jeh, Hakan, Lady Shr, and Rahven?
4. Does the crash occur every single time you encounter a monster on that level, or only some of the time? (One way to test might be to use the emulator to create a save state just before the monster.)

**Comment by tetracorp** [comment]
Actually, never mind these questions. I've done some tests with an edited map and various versions. Here's what I've discovered:

In both English and German, random combat encounters in the game's [final level](https://tetracorp.github.io/dungeons-of-avalon/maps/doa2-tower-b2.html) freeze in the manner you describe. It crashes every time I enter a random encounter on that level. That level is the one I designated B2, which has three stairways leading down to it from the level full of pits.

_However_, the updated 1995 German version of the game which came on the special cover CD-ROM does not display this bug. This is the one where the default party has level 16 characters Raymon, Phantic, etc. In other words, find a copy of this version, and the game should be completable.

**Comment by newcron** [comment]
Hi there!

wow that’s a lot of investigation! Thanks a lot :-)
I really appreciate the page you have made and the work you put into that project. 

It’s many years ago I played it - and I don’t think I can still find all the old save games anymore. But you should be right it was at B2. All I know for sure is having been in B1 (with all the magic dispels). Probably made it one level further than that. 

It was certainly all random monster encounters that caused the crash consistently  - I retried many, many times doing exactly that (the never ending optimism of kids I suppose). And it was definitely the floppy version. Amiga fun really didn’t have a lot of quality control back then. I had a subscription and half of their games didn’t work.
