### ISSUE TITLE
Level up - XP für Hlr/Kt/Thf falsch dargestellt

### ISSUE THREAD

**Issue by Sodocast** [tetracorp/dungeons-of-avalon#6]
Bei https://tetracorp.github.io/dungeons-of-avalon/game/character-creation-and-level.html sind für Hlr/Kt/Thf die Xp für den Stufenanstieg falsch angelgegeben. Der Multiplikator ist 8x der Basis XP. Level 2 benötigt daher bei Basis XP von 20 = 160 XP, Level 10 bei Basis XP von 1.100 schon 8.800 XP.

**Comment by tetracorp** [comment]
You're right. I checked the game code for both DoA1 and DoA2 to make sure, and the Healer, Knight and Thief (Heiler, Ritter, Dieb) are all x8. I've fixed the XP table. Danke
